spring:
  profiles:
    active: development
  data:
    rest:
      base-path: /api

---

spring:
  profiles: development
  datasource:
    platform: postgresql
  jpa:
    show-sql: true
    generate-ddl: true
debug: true

---

spring:
  profiles: production