spring:
  profiles:
    active: development

---

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: my-secret-pw
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
management:
  endpoints:
    web:
      expose: "*"
debug: true

---

spring:
  profiles: production