spring:
  profiles:
    active: development
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
flyway:
  locations: db/migration/{vendor}
server:
  contextPath: /api

---

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: my-secret-pw
  jpa:
    show-sql: true
endpoints:
  hypermedia:
    enabled: true
  sensitive: false
debug: true

---

spring:
  profiles: production