spring:
  profiles:
    active: development
  data:
    rest:
      base-path: /api

---

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
endpoints:
  hypermedia:
    enabled: true
  sensitive: false
debug: true

---

spring:
  profiles: production