spring:
  profiles:
    active: development
  data:
    rest:
      base-path: /api
flyway:
  locations: db/migration/{vendor}

---

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost/postgres
  jpa:
    show-sql: true
endpoints:
  hypermedia:
    enabled: true
  sensitive: false
debug: true

---

spring:
  profiles: production